version: "3.8"
services:
  db:
    image: postgres:13-bullseye
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ./postgres:/var/lib/postgres
    ports:
      - "5432:5432"

